FROM golang:1.6

# Set up environment variables
ENV RES_DIR /go/src/app
ENV LOG_DIR /go/src/app/log

# apt-get installs
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim tmux
RUN DEBIAN_FRONTEND=noninteractive apt-get update

WORKDIR /go/src/app
